export const SELL_GAMING_PRODUCT = 'SELL_GAMING_PRODUCT'
export const PURCHASE_NEW_BUSINESS = 'PURCHASE_NEW_BUSINESS'
export const HIRED_NEW_MANAGER = 'HIRED_NEW_MANAGER'
export const START_INITIAL = 'START_INITIAL'
export const START_CALCULATE_CAPITAL = 'START_CALCULATE_CAPITAL'

export const FETCH_GAMMING_SUCCESS = 'FETCH_GAMMING_SUCCESS'
export const FETCH_GAMMING_FAILURE = 'FETCH_GAMMING_FAILURE'
export const GET_GAMMING_DETAILS   = 'GET_GAMMING_DETAILS'